import { state, contacts, messages } from "./state.js";
import { showToast } from "./ui.js";
import { closeChat } from "./chat.js";
import {
	updateTotalUnreadCount,
	refreshCard,
	sortContacts,
	sortActiveChats,
} from "./chat-logic.js";
import { createContactCard } from "../../../components/contact-cards/contact-card.js";
import { createActiveChatCard } from "../../../components/active-chats/active-chats.js";
import { mountAvatar } from "../../../utils/dom.js";
import {
	updateContact,
	deleteContact as apiDeleteContact,
	deleteChat as apiDeleteChat,
	searchUsers,
} from "./api.js";

let _dom = {};
const _searchUsersCache = new Map();
const SEARCH_USERS_CACHE_TTL = 5 * 60 * 1000; // 5 minutes
// How the profile was opened ("dialog" on wide screens, "panel" on phones),
// so closing it works even if the window was resized in between.
let _profileMode = null;
// Where the panel lives in the page; it goes back there after being shown in
// the desktop dialog, so the phone layout can still find it.
let _panelHome = null;

/**

- @param {{
- contactProfileDetails, profileDialog, chatPart, peoplePart,
- detailPictures, detailNames, detailBios, detailLastSeens,
- detailUsernames, detailEmails,
- editNameDoneBtn, cancelEditNameBtn,
- chatEl, chatName, chatProfilePic,
- activeChatsContainer, contactsContainer,
- messageContainer, unblockActionBtn, unavailableNotice,
- deleteIcon
- }} dom
  */
export function initProfile(dom) {
	_dom = dom;
	const panel = dom.contactProfileDetails;
	if (panel && panel.parentNode) _panelHome = { parent: panel.parentNode, next: panel.nextSibling };
}

function _returnPanelHome() {
	const panel = _dom.contactProfileDetails;
	if (!panel) return;
	panel.style.display = "";
	if (_panelHome && _panelHome.parent && panel.parentNode !== _panelHome.parent) {
		const next = _panelHome.next && _panelHome.next.parentNode === _panelHome.parent ? _panelHome.next : null;
		_panelHome.parent.insertBefore(panel, next);
	}
}

/**
 * The message box under the chat: hidden for a blocked contact (with an
 * "Unblock" button instead) and for a deleted account (with a notice).
 */
export function applyComposerState(friend) {
	const input = _dom.messageContainer || null;
	const unblock = _dom.unblockActionBtn?.[0] || null;
	const notice = _dom.unavailableNotice || null;
	const deleted = !!friend?.isDeleted && !friend?.isSaved;
	const blocked = !deleted && !!friend?.isBlocked;
	if (input) input.style.display = deleted || blocked ? "none" : "flex";
	if (unblock) unblock.style.display = blocked ? "flex" : "none";
	if (notice) notice.style.display = deleted ? "flex" : "none";
}

// last seen format
function formatLastSeen(isoString) {
	const diff = Math.floor((Date.now() - new Date(isoString)) / 1000);
	if (diff < 60) return "just now";
	if (diff < 3600) return `${Math.floor(diff / 60)} minutes ago`;
	if (diff < 86400) return `${Math.floor(diff / 3600)} hours ago`;
	if (diff < 172800) return "yesterday";
	if (diff < 604800) return `${Math.floor(diff / 86400)} days ago`;
	if (diff < 1209600) return "last week";
	if (diff < 2592000) return `${Math.floor(diff / 604800)} weeks ago`;
	if (diff < 5184000) return "last month";
	return `${Math.floor(diff / 2592000)} months ago`;
}

// mountAvatar() replaces the picture element, so the <img> captured at start-up
// is detached after the first profile and never updated again (every profile
// kept showing the first contact's picture). Mount into the container instead,
// looked up inside the panel: on desktop the panel is out of the page while closed.
function _mountDetailPicture(friend) {
	(_dom.contactProfileDetails || document).querySelectorAll(".detail-picture").forEach((el) =>
		mountAvatar(el, {
			name: friend.name,
			nickname: friend.nickname,
			profilePics: friend.profilePics,
			className: "contact-profile",
			isOnline: friend.isOnline,
			isDeleted: !!friend.isDeleted,
		}),
	);
}

function _blockButtonsText(isBlocked) {
	_dom.contactProfileDetails
		?.querySelectorAll("#block-contact-btn")
		.forEach((btn) => (btn.textContent = isBlocked ? "Unblock contact" : "Block contact"));
}

// Fills the profile panel with this contact's details
function _fillProfile(friend) {
	_mountDetailPicture(friend);
	_dom.detailNames.forEach(
		(el) => (el.textContent = friend.nickname || friend.name),
	);
	_dom.detailBios.forEach((el) => (el.textContent = friend.bio || ""));
	_dom.detailLastSeens.forEach(
		(el) =>
			(el.textContent = friend.isDeleted
				? ""
				: friend.isOnline
					? "Online"
					: friend.lastSeen
						? `Last seen ${formatLastSeen(friend.lastSeen)}`
						: ""),
	);
	// If the account was anonymized/deleted on the server, avoid showing
	// the autogenerated placeholder username/email (they look garbled).
	const isDeletedAccount =
		!!friend.isDeleted ||
		String(friend.contact?.name || "").toLowerCase() === "deleted account";
	const isAnonPlaceholder = (friend.username && String(friend.username).startsWith("deleted_user_")) || (friend.email && String(friend.email).endsWith("@deleted.rivo"));
	const hidePersonal = isDeletedAccount || isAnonPlaceholder;

	_dom.detailUsernames.forEach((el) => (el.textContent = hidePersonal || !friend.username ? "" : "@" + friend.username));
	_dom.detailEmails.forEach((el) => (el.textContent = hidePersonal ? "" : (friend.email || "")));

	_blockButtonsText(!!friend.isBlocked);
	_dom.contactProfileDetails.querySelectorAll("#archive-contact-btn").forEach((btn) => {
		btn.textContent = friend.isArchived ? "Unarchive Chat" : "Archive Chat";
	});

	// Copy on tap, only when personal info is shown
	const copyable = (el, value, shown) => {
		if (hidePersonal || !value) {
			el.style.cursor = "default";
			el.onclick = null;
			return;
		}
		el.style.cursor = "pointer";
		el.onclick = () => {
			navigator.clipboard?.writeText(value).catch(() => {});
			el.textContent = "Copied!";
			setTimeout(() => {
				el.textContent = shown;
			}, 1500);
		};
	};
	_dom.detailUsernames.forEach((el) => copyable(el, friend.username ? `@${friend.username}` : "", "@" + friend.username));
	_dom.detailEmails.forEach((el) => copyable(el, friend.email || "", friend.email || ""));
	return hidePersonal;
}

/** Updates the open profile after the contact's details changed. */
export function refreshProfile(friend) {
	if (!friend || !state.isProfileDialogOpen || state.contactUserId !== friend.id) return;
	// a nickname being typed is not overwritten
	const editing = _dom.detailNames?.[0]?.getAttribute("contenteditable") === "true";
	const typed = editing ? _dom.detailNames[0].textContent : null;
	_fillProfile(friend);
	if (editing) _dom.detailNames.forEach((el) => (el.textContent = typed));
}

// ─── Open profile ─────────────────────────────────────────────────────────────
export async function openProfile(friend) {
	const hidePersonal = _fillProfile(friend);

	// Show the profile first: the bio lookup below must not delay it
	if (window.innerWidth > 700) {
		_profileMode = "dialog";
		if (_dom.profileDialog) {
			// an inline display left by the phone layout would hide it here
			_dom.contactProfileDetails.style.display = "";
			_dom.contactProfileDetails.classList.remove("slide-in", "slide-out");
			_dom.profileDialog.appendChild(_dom.contactProfileDetails);
			if (!_dom.profileDialog.open) _dom.profileDialog.showModal();
		}
	} else {
		_profileMode = "panel";
		_returnPanelHome();
		_dom.contactProfileDetails.style.display = "flex";
		_dom.contactProfileDetails.classList.remove("slide-out");
		_dom.contactProfileDetails.classList.add("slide-in");
		_dom.contactProfileDetails.addEventListener(
			"animationend",
			() => {
				_dom.contactProfileDetails.classList.remove("slide-in");
			},
			{ once: true },
		);
	}
	state.isProfileDialogOpen = true;

	// If bio is missing, try to resolve via username lookup. Use a simple
	// in-memory cache to avoid repeated network calls when the profile is
	// opened/closed quickly.
	if ((!friend.bio || friend.bio === "") && friend.username && !hidePersonal) {
		try {
			let users;
			const key = friend.username;
			const entry = _searchUsersCache.get(key);
			if (entry && Date.now() - entry.ts < SEARCH_USERS_CACHE_TTL) {
				users = entry.data;
			} else {
				users = await searchUsers(friend.username);
				_searchUsersCache.set(key, { data: users, ts: Date.now() });
			}
			// the user may have opened another profile meanwhile
			if (!state.isProfileDialogOpen || state.contactUserId !== friend.id) return;
			if (Array.isArray(users) && users.length > 0) {
				const found = users.find(
					(u) =>
						String(u.username).toLowerCase() ===
						String(friend.username).toLowerCase(),
				);
				if (found && found.bio) {
					friend.bio = found.bio;
					_dom.detailBios.forEach((el) => (el.textContent = friend.bio || ""));
				}
			}
		} catch (e) {
			/* ignore lookup errors */
		}
	}
}

// ─── Close profile ────────────────────────────────────────────────────────────
export function closeProfile() {
	// Reset any open nickname edit
	_dom.detailNames.forEach((el) => {
		el.setAttribute("contenteditable", "false");
		el.style.border = "none";
	});
	_dom.editNameDoneBtn?.forEach((el) => (el.style.display = "none"));
	_dom.cancelEditNameBtn?.forEach((el) => (el.style.display = "none"));

	const mode = _profileMode || (window.innerWidth > 700 ? "dialog" : "panel");
	_profileMode = null;
	if (mode === "dialog") {
		try {
			if (_dom.profileDialog?.open) _dom.profileDialog.close();
		} catch (e) { /* ignore */ }
		_returnPanelHome();
		state.skipShowChatOnProfileClose = false;
	} else {
		const panel = _dom.contactProfileDetails;
		const finish = () => {
			panel.classList.remove("slide-out");
			panel.style.display = "none";
			if (!state.skipShowChatOnProfileClose) {
				if (state.contactUserId !== null) _dom.chatPart.style.display = "flex";
			} else {
				state.skipShowChatOnProfileClose = false;
			}
		};
		// an invisible panel never fires animationend
		if (!panel.isConnected || getComputedStyle(panel).display === "none") {
			finish();
		} else {
			panel.classList.remove("slide-in");
			panel.classList.add("slide-out");
			panel.addEventListener("animationend", finish, { once: true });
		}
	}
	state.isProfileDialogOpen = false;
}

function _cardsOf(contactId) {
	const selector = `[data-user-id="${contactId}"], [data-wrapper-user-id="${contactId}"]`;
	const nodes = [];
	[_dom.activeChatsContainer, _dom.contactsContainer].forEach((root) => {
		root?.querySelectorAll(selector).forEach((el) => {
			const wrapper = el.closest(".active-chat-wrapper") ?? el;
			if (wrapper && !nodes.includes(wrapper)) nodes.push(wrapper);
		});
	});
	return nodes;
}

// Closes the profile and the chat when they show this contact
function _closeIfShowing(contactId) {
	if (state.contactUserId !== contactId) return;
	state.skipShowChatOnProfileClose = true;
	if (state.isProfileDialogOpen) closeProfile();
	else state.skipShowChatOnProfileClose = false;
	if (_dom.chatEl) _dom.chatEl.textContent = "";
	closeChat();
}

// ─── Delete chat ──────────────────────────────────────────────────────────────
// Removes every message of the conversation, for both people.
export function handleDeleteChat(targetId = state.contactUserId) {
	const deletingContactId = targetId;
	const contact = contacts.find((c) => c.id === deletingContactId);
	if (!contact) return;

	// record original desired container so undo can restore correctly
	// Saved messages should always be considered part of the active chats
	const originalContainer = contact.isSaved
		? "active"
		: _dom.activeChatsContainer?.querySelector(`[data-user-id="${deletingContactId}"]`)
			? "active"
			: "contacts";

	_closeIfShowing(deletingContactId);

	// Fade any matching cards in both lists (active and contacts)
	_cardsOf(deletingContactId).forEach((wrapper) => {
		wrapper.style.transition = "opacity 3s ease";
		wrapper.style.opacity = "0";
		wrapper.style.pointerEvents = "none";
	});

	showToast("Chat deleted", _dom.deleteIcon, true);

	const timer = setTimeout(() => {
		const contact = contacts.find((c) => c.id === deletingContactId);
		_cardsOf(deletingContactId).forEach((el) => el.remove());

		messages[deletingContactId] = [];

		if (contact) {
			if (contact.conversationId) {
				apiDeleteChat(contact.conversationId).catch(() => {
					showToast("Couldn't delete the chat. Try again.");
				});
			}
			contact.lastMessage = "";
			contact.lastMessageId = null;
			contact.lastMessageTime = "";
			contact.lastMessageDate = "";
			contact.lastMessageTs = 0;
			contact.lastMessageSeen = true;
			contact.unreadCount = 0;

			if (contact.isSaved || contact.isPinned) {
				// Saved Messages and pinned chats stay in Active Chats
				const newCard = createActiveChatCard(contact);
				if (contact.isSaved) _dom.activeChatsContainer.prepend(newCard);
				else _dom.activeChatsContainer.appendChild(newCard);
				sortActiveChats();
			} else if (!contact.isArchived) {
				// Final state after delete should be a plain contact card
				_dom.contactsContainer.appendChild(
					createContactCard(
						{ ...contact, hasMessages: false },
						_dom.onContactAction,
					),
				);
			}
		}

		updateTotalUnreadCount();
		sortContacts();
	}, 3000);

	state.currentUndoAction = () => {
		clearTimeout(timer);
		try {
			const contactObj = contacts.find((c) => c.id === deletingContactId);
			if (!contactObj) return;
			const existingActive = _dom.activeChatsContainer?.querySelector(
				`[data-user-id="${contactObj.id}"]`,
			);
			const existingContact = _dom.contactsContainer?.querySelector(
				`[data-user-id="${contactObj.id}"]`,
			);

			if (originalContainer === "contacts") {
				// ensure not duplicated in active list
				if (existingActive) {
					const wrapper =
						existingActive.closest(".active-chat-wrapper") ??
						existingActive;
					if (wrapper) wrapper.remove();
				}
				if (!existingContact) {
					_dom.contactsContainer.appendChild(
						createContactCard(
							{
								...contactObj,
								hasMessages: !!contactObj.lastMessage,
							},
							_dom.onContactAction,
						),
					);
				} else {
					existingContact.style.transition = "opacity 0.2s ease";
					existingContact.style.opacity = "1";
					existingContact.style.pointerEvents = "";
				}
			} else {
				// restore to active chats
				if (existingContact) existingContact.remove();
				if (!existingActive) {
					_dom.activeChatsContainer.appendChild(
						createActiveChatCard(contactObj),
					);
				} else {
					const wrapper =
						existingActive.closest(".active-chat-wrapper") ??
						existingActive;
					if (wrapper) {
						wrapper.style.transition = "opacity 0.2s ease";
						wrapper.style.opacity = "1";
						wrapper.style.pointerEvents = "";
					}
				}
			}

			updateTotalUnreadCount();
			sortActiveChats();
			sortContacts();
		} catch (e) {
			/* ignore */
		}
	};
}

// ─── Edit nickname ────────────────────────────────────────────────────────────
export function handleEditNickname() {
	_dom.detailNames.forEach((el) => {
		el.setAttribute("contenteditable", "true");
		el.style.border = "1px solid var(--chat-time)";
		el.focus();
		const range = document.createRange();
		const sel = window.getSelection();
		range.selectNodeContents(el);
		range.collapse(false);
		sel.removeAllRanges();
		sel.addRange(range);
		// Enter saves instead of starting a new line
		el.onkeydown = (e) => {
			if (e.key === "Enter") {
				e.preventDefault();
				handleEditNicknameDone();
			} else if (e.key === "Escape") {
				e.preventDefault();
				handleEditNicknameCancel();
			}
		};
	});
	const editNameDoneBtn1 = _dom.editNameDoneBtn?.[0];
	if (editNameDoneBtn1) editNameDoneBtn1.style.display = "block";
	const cancelEditNameBtn1 = _dom.cancelEditNameBtn?.[0];
	if (cancelEditNameBtn1) cancelEditNameBtn1.style.display = "block";
}

function _endNicknameEdit() {
	_dom.detailNames.forEach((el) => {
		el.setAttribute("contenteditable", "false");
		el.style.border = "none";
		el.onkeydown = null;
	});
	_dom.editNameDoneBtn.forEach((el) => (el.style.display = "none"));
	_dom.cancelEditNameBtn.forEach((el) => (el.style.display = "none"));
}

function _showName(friend) {
	const shown = friend.nickname || friend.name;
	_dom.detailNames.forEach((el) => (el.textContent = shown));
	if (state.contactUserId === friend.id && _dom.chatName) _dom.chatName.textContent = shown;
	refreshCard(friend);
}

export function handleEditNicknameDone() {
	const friend = contacts.find((c) => c.id === state.contactUserId);
	if (!friend) return;
	const firstDetailName = _dom.detailNames?.[0];
	const typed = firstDetailName && firstDetailName.textContent
		? firstDetailName.textContent.replace(/\s+/g, " ").trim().slice(0, 100)
		: "";
	_endNicknameEdit();

	const before = { nickname: friend.nickname, name: friend.name };
	const realName = friend.contact?.name || friend.name;
	if (typed && typed !== (friend.nickname || friend.name)) {
		friend.nickname = typed;
	} else if (!typed && friend.nickname) {
		// an empty name goes back to the contact's own name
		friend.nickname = null;
		friend.name = realName;
	} else {
		_showName(friend);
		return;
	}
	_showName(friend);
	updateContact(friend.id, { nickname: friend.nickname || "" }).catch(() => {
		friend.nickname = before.nickname;
		friend.name = before.name;
		_showName(friend);
		showToast("Couldn't change the name. Try again.");
	});
}

export function handleEditNicknameCancel() {
	const friend = contacts.find((c) => c.id === state.contactUserId);
	_endNicknameEdit();
	if (!friend) return;
	_dom.detailNames.forEach((el) => {
		el.textContent = friend.nickname || friend.name;
	});
}

// ─── Block / Unblock contact ──────────────────────────────────────────────────
function _applyBlockUi(contact) {
	if (state.contactUserId === contact.id) {
		_blockButtonsText(contact.isBlocked);
		applyComposerState(contact);
	}
	refreshCard(contact);
	// blocked contacts are listed last
	sortContacts();
}

export function handleBlockContact(targetId = state.contactUserId) {
	const contact = contacts.find((c) => c.id === targetId);
	if (!contact || contact.isSaved) return;
	const next = !contact.isBlocked;
	contact.isBlocked = next;
	_applyBlockUi(contact);
	updateContact(contact.id, { isBlocked: next })
		.then(() => showToast(next ? "Contact blocked" : "Contact unblocked"))
		.catch(() => {
			contact.isBlocked = !next;
			_applyBlockUi(contact);
			showToast("Couldn't update. Try again.");
		});
}

// ─── Delete contact ───────────────────────────────────────────────────────────
export function handleDeleteContact(targetId = state.contactUserId) {
	const deletingContactId = targetId;
	const contactObj = contacts.find((c) => c.id === deletingContactId);
	if (!contactObj || contactObj.isSaved) return;

	// Determine where this contact was so undo can restore correctly
	const originalContainer = _dom.activeChatsContainer?.querySelector(
		`[data-user-id="${deletingContactId}"]`,
	)
		? "active"
		: "contacts";

	// Hide it first
	_cardsOf(deletingContactId).forEach((card) => {
		card.style.transition = "opacity 3s ease";
		card.style.opacity = "0";
		card.style.pointerEvents = "none";
	});

	// Close the profile first, then the chat after the profile slide-out
	// animation completes (on phones).
	const wasShowing = state.contactUserId === deletingContactId;
	if (wasShowing) {
		state.skipShowChatOnProfileClose = true;
		if (state.isProfileDialogOpen) closeProfile();
		else state.skipShowChatOnProfileClose = false;
	}
	setTimeout(() => {
		if (wasShowing && state.contactUserId === deletingContactId) closeChat();
		showToast("Contact deleted", _dom.deleteIcon, true);
	}, wasShowing ? 350 : 0);

	const timer = setTimeout(() => {
		// look the contact up again: the list may have changed meanwhile
		const idx = contacts.findIndex((c) => c.id === deletingContactId);
		if (idx === -1) return;
		const [removed] = contacts.splice(idx, 1);
		_cardsOf(deletingContactId).forEach((el) => el.remove());
		delete messages[deletingContactId];
		updateTotalUnreadCount();
		sortContacts();
		apiDeleteContact(deletingContactId).catch(() => {
			// the server still has it: put it back
			if (!contacts.some((c) => c.id === removed.id)) contacts.push(removed);
			if (originalContainer === "active" && !removed.isArchived) {
				_dom.activeChatsContainer.appendChild(createActiveChatCard(removed));
				sortActiveChats();
			}
			sortContacts();
			updateTotalUnreadCount();
			showToast("Couldn't delete the contact. Try again.");
		});
	}, 3000);

	state.currentUndoAction = () => {
		clearTimeout(timer);
		try {
			// restore the visual card in the original container
			const existingActive = _dom.activeChatsContainer?.querySelector(
				`[data-user-id="${deletingContactId}"]`,
			);
			const existingContact = _dom.contactsContainer?.querySelector(
				`[data-user-id="${deletingContactId}"]`,
			);

			if (originalContainer === "contacts") {
				if (existingActive) {
					const w =
						existingActive.closest(".active-chat-wrapper") ??
						existingActive;
					if (w) w.remove();
				}
				if (!existingContact) {
					_dom.contactsContainer.appendChild(
						createContactCard(
							{
								...contactObj,
								hasMessages: !!contactObj.lastMessage,
							},
							_dom.onContactAction,
						),
					);
				} else {
					existingContact.style.transition = "opacity 0.2s ease";
					existingContact.style.opacity = "1";
					existingContact.style.pointerEvents = "";
				}
			} else {
				if (existingContact) existingContact.remove();
				if (!existingActive) {
					_dom.activeChatsContainer.appendChild(
						createActiveChatCard(contactObj),
					);
				} else {
					const wrapper =
						existingActive.closest(".active-chat-wrapper") ??
						existingActive;
					if (wrapper) {
						wrapper.style.transition = "opacity 0.2s ease";
						wrapper.style.opacity = "1";
						wrapper.style.pointerEvents = "";
					}
				}
			}

			updateTotalUnreadCount();
			sortActiveChats();
			sortContacts();
		} catch (e) {
			/* ignore */
		}
	};
}
